language: cpp
root: true
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - echo $LANG
  - echo $LC_ALL
  - export CXXFLAGS="$CXXFLAGS -std=gnu++11";
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update                ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install swig r-base; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update        ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install swig r; fi
install:
  - if test -n "$CPP11"; then CONFIGOPTS+=(--enable-cpp11-testing --without-maximum-compile-warnings "CXXFLAGS=-std=c++11 -Wall -Wextra" "CFLAGS=-std=c11 -Wall -Wextra") && export CSTD=c11 && export CPPSTD=c++11; fi
jobs:
  allow_failures:
    - compiler: clang
script:
  - $CXX --version     
  - make
notifications:
  email:
    on_success: change
    on_failure: change
env:	CPP11=1