---
title: "ImageCompression"
author: "Andreas M. Brandmaier"
date: "1/1/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


  dyn.load(paste("../bnnlib", .Platform$dynlib.ext, sep=""))
  source("../bnnlib.R")
  cacheMetaData(1)
  
source("../R/toSequence.R")
source("../R/banana.R")
```

## Load Images

```{r cars}
library(png)
library(raster)

images <- c("bottle1.png","bottle2.png","bottle3.png","fish1.png","fish2.png","fish3.png")

path<-"../OpenclipartShapes/"


sw<-function(pic)
{
	temp <- (pic[,,1]+pic[,,2]+pic[,,3])/3
	return(as.matrix(temp))
}

downsample<-function(pic)
{
  pic[seq(1,1000,12),seq(1,1000,12)]
}


sequence_set <- SequenceSet()

for (fname in images) {
  img <- readPNG(paste0(path,fname))
  img <- downsample(sw(img))


  data.row <- as.vector(img)
  data.row <- data.frame(t(data.row)) # 1x 7056

ln <- length(img)

sequence <- toSequence(data.row, 1:ln, 1:ln)

SequenceSet_add_copy_of_sequence(sequence_set, sequence)
}
```

## Create auto-associator

```{r pressure, echo=FALSE}
dim <- 84
dims <- dim*dim
```

## Feedforward Neural Network

Create a feed-forward neural network with $84^2$ inputs, 4 hidden units, and $84^2$ output. The output node is linear.

```{r}
LINEAR_NODE = 3
num_hidden = 64
#net <- NetworkFactory_createFeedForwardNetwork(dims,4,dims, LINEAR_NODE)
net <- NetworkFactory_createSparseAutoencoder(dims,num_hidden,0.01, TANH_NODE, TANH_NODE)
```


Initialize training algorithm

```{r}
trainer <- ImprovedRPropTrainer(net)

cat("Using Trainer: ",Trainer_get_name(trainer),"\n")

 Network_evaluate_training_error__SWIG_0(net, sequence_set)
 
 
Trainer_sparsity_beta_set(trainer,1000)
 
Sys.time()
Trainer_train__SWIG_0(trainer, sequence_set, 50)
Sys.time()

Network_evaluate_training_error__SWIG_0(net, sequence_set)


source("../R/plotTrainingerror.R")
plotTrainingerror(trainer)
 
```

Obtain hidden activations

```{r outputpredictedimage}
sequence = SequenceSet_get(sequence_set,2)
# convert this back into an image
#x = getActivations(net, sequence)
x = getOutputs(net, sequence )
#x2 = sapply(1:(84*84), function(x){ Sequence_get_input_at(sequence,0,x-1)})
x2 = getInputs(sequence)
#getInputs()
predimg <- matrix(nrow=dim, ncol=dim)
inpimg <- matrix(nrow=dim, ncol=dim)
for (i in 1:dim) {
  predimg[i,] <- x[1:dim+(i-1)*dim]
  inpimg[i,] <- x2[1:dim+(i-1)*dim]
}
par(mfrow=c(2,2))
image(predimg)
image(inpimg)
image(predimg-inpimg)
image(abs(predimg-inpimg))
```

# Plot latent space projections

```{r}
source("../R/plotActivations.R")
#plotActivations(net, sequence, node.names = c("Hidden0","Hidden1","Hidden2","Hidden3"))

pos <- which(sapply(getNodeNames(net) , function(x){startsWith(x,"Hidden")}))
#pos <- 7630:7670
result <- matrix(nrow=0,ncol=length(pos))
for (i in 1:SequenceSet_size(sequence_set)) {
  sequence <- SequenceSet_get(sequence_set,i-1)
  x = getActivations(net, sequence)[1,pos]
  result <- rbind(result, x)
}

result

coords <- cmdscale(dist(result),2)
plot(coords,type="n")
text(x=coords[,1],y=coords[,2], labels=images)

```