---
title: "Parity"
author: "Andreas M. Brandmaier"
date: "12/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

First, we load the shared library.

```{r load, echo=TRUE}


  dyn.load(paste("../bnnlib", .Platform$dynlib.ext, sep=""))
  source("../bnnlib.R")
  cacheMetaData(1)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
library(reshape2)
library(ggplot2)
maxx <- 20
raw <- read.csv("../datasets/parity.dat")[,1]
x <- raw[seq(1,maxx,2)] # take every other
y <- raw[seq(2,maxx,2)] # take every other
dat <- rbind(x,y)
#colnames(dat) <- c("A","B")
mdat <- melt(dat)
mdat$value <- factor(mdat$value)
library(reshape2)
ggplot(data=mdat, aes(x=Var2,y=Var1,fill=value))+geom_raster()+
  xlab("Input/Output")+ylab("Time")
```

Start training



```{r training, echo=FALSE}

#TANH_NODE = 3
#layers = c(4,4)
#network = NetworkFactory_createRecurrentNetwork(1,4,1)

network = LSTMNetwork(1,1,1)

training_set = SequenceSet("../datasets/parity.dat")

SequenceSet_get_input_size(training_set)
SequenceSet_get_target_size(training_set)

trainer = ImprovedRPropTrainer(network);
		
	T#rainer_learning_rate_set( trainer, 0.0001 );

#Trainer_batch_learning_set(trainer, TRUE)


#	trainer->abort_criteria.push_back( new ConvergenceCriterion(10e-7) );

#Trainer_add_abort_criterion( ConvergenceCriterion(.00001))

	Trainer_train2(trainer, training_set, 1000)

	


	#net->export_to_dot_graph("graph");

#		x = Network_test_sequence( network, training_set, TRUE)	#
#		values <- .Call('R_swig_toValue',  Trainer_error_train_get(trainer), package="bnnlib") 
#	library(ggplot2)#
#	ggplot2::ggplot(data.frame(x=1:length(values),values),aes(x=x,y=values))+geom_point()+
#	  geom_line()+geom_smooth()	
		
		seq1 <- SequenceSet_get(training_set,0)
#		Network_activate_and_return_activations()

		#		Network_activate_and_return_activations(network, )
		

	
	

```

Collect outputs

```{r}
 Network_activate(network, seq1)
ln <-Sequence_size(seq1)
  vals <- rep(NA,ln)
  trt <- rep(NA, ln)
  for (i in 1:ln) {
		outp <- Network_get_output(network,i-1)
		vals[i] <- .Call('R_swig_toValue',  outp, package="bnnlib") 
		outp <- Sequence_get_target(seq1, i-1)
		trt[i] <- .Call('R_swig_toValue',  outp, package="bnnlib") 
  }
  print(vals)
  plot(vals)
  points(trt, col="green")
```


