---
title: "Trainer"
author: "Andreas M. Brandmaier"
date: "12/12/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Library

```{r pressure, echo=FALSE}


  dyn.load(paste("../bnnlib", .Platform$dynlib.ext, sep=""))
  source("../bnnlib.R")
  cacheMetaData(1)

```

## Generate Data

```{r}
source("../R/toSequence.R")
set <- SequenceSet()
N <- 100
M <- 5
simdata <- data.frame(matrix(data=rnorm(N*M),nrow = N))
simdata[,M] <- simdata[,1]+simdata[,2]-3*simdata[,3]
seq <- toSequence(simdata,1:4,5)
SequenceSet_add_sequence(set, seq)

Sequence_get_target_size(seq)
Sequence_get_input_size(seq)
```

## Create Network

```{r}
net <- NetworkFactory_createFeedForwardNetwork(M-1,5,1,3)
```

## Trainer

```{r}
trainer <- list(CGTrainer(net), BackpropTrainer(net), ImprovedRPropTrainer(net),
ARPropTrainer(net) )

steps <- 100
err.data <- matrix(data=NA,nrow=length(trainer)*steps,ncol=3)
err.data <- data.frame(err.data)
names(err.data) <- c("error","trainer","step")
k <- 1

for (i in 1:length(trainer)) {
  tt <- trainer[[i]]
  Network_reinitialise(net)

  for (j in 1:steps) {
    Trainer_train__SWIG_0(tt, set, 1)
    err.data[k,1] <- Network_evaluate_training_error__SWIG_0(net, set)
    err.data[k,2] <- Trainer_get_name(tt)
    err.data[k,3] <- j
    k<-k+1
  }
}

err.data$trainer<-factor(err.data$trainer)
```

Plot errors

```{r}
library(ggplot2)

ggplot(data=err.data, aes(x=step,y=error,group=trainer,col=trainer))+geom_point()+geom_line()
```